<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.zhanghslq</groupId>
        <artifactId>muskit-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>muskit-bom</artifactId>
    <packaging>pom</packaging>
    <name>Muskit BOM</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-test-support</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-context-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-context-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-context</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-concurrency-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-concurrency-redis-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-concurrency-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-concurrency</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-concurrency-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-lock-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-lock-redis-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-lock-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-lock</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-idempotency-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-idempotency-jdbc-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-idempotency-redis-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-idempotency-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-idempotency-jdbc</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-idempotency-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-idempotency-kafka-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-idempotency-rabbit-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-idempotency-http-spring-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-resilience-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-resilience-redis-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-resilience4j-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-resilience-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-resilience</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-resilience-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-resilience4j</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-observation-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-observation-micrometer-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-observation-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-observability</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-lifecycle-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-lifecycle-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-lifecycle</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-executor-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-executor-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-executor</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-inbox-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-inbox-jdbc-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-inbox-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-inbox-jdbc</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-cache-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-cache-redis-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-cache-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-cache-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-client-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-client-spring-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-client-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-audit-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-audit-jdbc-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-audit-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-audit-jdbc</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-state-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-state-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-state</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-outbox-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-outbox-jdbc-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-outbox-kafka-adapter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-outbox-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zhanghslq</groupId>
                <artifactId>muskit-spring-boot-starter-outbox</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
