<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>io.github.zhanghslq</groupId><artifactId>muskit-parent</artifactId><version>0.1.0-SNAPSHOT</version><relativePath>../../pom.xml</relativePath></parent>
    <artifactId>muskit-spring-boot-starter-client</artifactId><name>Muskit Spring Boot Starter Client</name>
    <dependencies>
        <dependency><groupId>io.github.zhanghslq</groupId><artifactId>muskit-client-spring-boot-autoconfigure</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>io.github.zhanghslq</groupId><artifactId>muskit-client-spring-adapter</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>io.github.zhanghslq</groupId><artifactId>muskit-spring-boot-starter-context</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>io.github.zhanghslq</groupId><artifactId>muskit-spring-boot-starter-resilience</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-restclient</artifactId></dependency>
    </dependencies>
</project>
